from pathlib import Path
import csv,json,re,html,hashlib,struct,datetime,zipfile
R=Path(__file__).resolve().parent
H=html.escape
now=datetime.datetime.now(datetime.timezone.utc).isoformat(timespec='seconds')
def read(n):return (R/n).read_text(encoding='latin1').strip()
def savecsv(name,heads,rows):
 with (R/name).open('w',newline='',encoding='utf-8-sig') as f:
  w=csv.writer(f);w.writerow(heads);w.writerows(rows)
def tab(heads,rows,cls=''):
 return '<div class="table-wrap"><table class="'+cls+'"><thead><tr>'+''.join('<th>'+H(str(x))+'</th>' for x in heads)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+H(str(x))+'</td>' for x in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def pre(n):return '<pre>'+H(read(n))+'</pre>'
def link(url,label):return '<a href="'+H(url,quote=True)+'">'+H(label)+'</a>'
def p(s):return '<p>'+s+'</p>'
def details(title,body):return '<details><summary>'+H(title)+'</summary>'+body+'</details>'
sections=[]
def section(id,title,body):sections.append((id,title,'<section id="'+id+'"><h2>'+H(title)+'</h2>'+body+'</section>'))
native=[l.split('\t') for l in read('native.tsv').splitlines()]
loaded=[]
for a in native:
 if a[0] in ('LIB','DEV'):
  loaded.append([a[0],a[1],a[2]+'.'+a[3],a[4],'0x'+a[5],a[6],a[7],'0x'+a[8],a[9].strip() if len(a)>9 else ''])
savecsv('loaded-libraries-and-devices.csv',['Kind','Name','Header version','Open count','Base address','Negative bytes','Positive bytes','Flags','Embedded ID string'],loaded)
files=[]
for l in read('system-files.txt').splitlines():
 a=l.strip('*"').split('|')
 if len(a)==5:files.append(a)
assert len(files)==2763
savecsv('system-files.csv',['Path','Bytes','Filesystem date (Amiga clock)','Filesystem time','Protection'],files)
meta={r[0].lower():r for r in files}
versions=[]
for i in range(11):
 for block in read(f'versions-{i}.txt').split('@@')[1:]:
  a=block.strip().splitlines();path=a[0];v=' | '.join(a[1:]);m=meta.get(path.lower(),[path,'','','',''])
  versions.append([path,v,m[1],m[2],m[3],m[4]])
assert len(versions)==494
savecsv('installed-component-versions.csv',['Path','Version FILE FULL output','Bytes','Filesystem date (Amiga clock)','Filesystem time','Protection'],versions)
versionmap={r[0].lower():r[1] for r in versions}
ver=lambda name:versionmap.get(name.lower(),'Not queried')
libs=[r for r in loaded if r[0]=='LIB'];devs=[r for r in loaded if r[0]=='DEV']
resources=[a[1:] for a in native if a[0]=='RESOURCE']
fs=[l.split('\t') for l in read('filesystems.tsv').splitlines() if l.strip()]
savecsv('filesystem-resources.csv',['DOS type','Version','Priority','ID string'],fs)
boards=[]
boardnames={(5080,148):'Probable TF4060 / IDE function; model supplied by owner; serial field 4060 supports attribution',(28014,4):'MNT ZZ9000 graphics / registers',(28014,5):'MNT ZZ9000 Fast RAM',(4626,0):'Individual Computers Buddha IDE',(5191,30):'Freeway Triton Zorro III USB (ID pair matched in supplied driver)',(4626,100):'Individual Computers X-Surf 100'}
for a in native:
 if a[0]=='BOARD':
  m,q=int(a[1]),int(a[2]);boards.append([boardnames.get((m,q),'Unidentified'),f'{m} / {q}',f'${m:04X} / ${q:02X}','$'+a[3].upper(),int(a[4]),a[5],a[6],a[7]])
savecsv('expansion-boards.csv',['Identification','Manufacturer/product decimal','Manufacturer/product hex','Address','ConfigDev bytes','ROM type hex','Flags hex','AutoConfig serial field'],boards)
hardware=[
 ['Motherboard','Amiga A4000TX','Owner identification; AGA and memory/expansion configuration corroborate it','PCB revision, assembly date and serial not remotely established'],
 ['Accelerator','Terrible Fire TF4060','Owner identification; 68060, ehide driver and AutoConfig serial 4060 corroborate','Board revision, FPGA/CPLD firmware and actual CPU MHz unknown'],
 ['Main CPU','Motorola-compatible 68060, revision 5','Live CPU and ShowConfig','Full/LC/EC package marking and mask/date codes require physical inspection'],
 ['FPU and MMU','68060 MMU; FPU capability reported','Live CPU/Exec capability flags','OS labels FPU “68882”; this is not evidence of a separate active 68882 chip'],
 ['CPU caches','Instruction cache/burst; data cache/copyback; superscalar, store buffer, branch cache enabled','Live CPU command','No clock-changing or cache-changing command run'],
 ['AGA Alice','AGA PAL Alice R2, ID $0023','Live ShowConfig','Physical package/date code unknown'],
 ['AGA Lisa','AGA Lisa, ID $00F8','Live ShowConfig','No physical package/date-code inspection'],
 ['Paula audio/I/O','Paula audio driver active; native audio.device loaded','Live OS/driver evidence','Exact Paula revision/package not read electronically'],
 ['CIA A / CIA B','ciaa.resource and ciab.resource registered','Live Exec resources','Resource names confirm OS interfaces; no individual chip date/revision read'],
 ['Other motherboard logic','Buster / Ramsey / Gary and supporting clock, RTC and glue logic','Expected A4000-class architecture, not individually inventoried','Exact silicon, revisions, programmable-logic versions and clock oscillator markings unknown'],
 ['ZZ9000','MNT ZZ9000 in Zorro III mode','Live AutoConfig IDs 28014/4 and 28014/5','Physical PCB revision and serial unavailable'],
 ['ZZ9000 processor/FPGA','Xilinx Zynq XC7Z020: dual ARM Cortex-A9, nominal 666 MHz; FPGA fabric','Manufacturer specification; prior ARM Core1 execution verified','Core count, silicon stepping and physical markings not freshly probed'],
 ['ZZ9000 DDR3','1 GB onboard DDR3 per manufacturer; 256 MiB exposed as Amiga Fast RAM','Specification plus live RAM AutoConfig','The remaining DDR is not automatically additional AmigaOS RAM'],
 ['Ethernet','Individual Computers X-Surf 100, ShowConfig identifies Rev 3 ZII/ZIII','Live AutoConfig and active network driver','Current device reports 100,000,000 bit/s; PHY/controller chip markings unverified'],
 ['IDE controller','Individual Computers Buddha IDE; buddha.device and 2nd.buddha.device 52.110','Live AutoConfig, drivers and mounted drives','Board flash build date and exact PCB revision not obtained'],
 ['USB controller','Freeway Triton Lite (owner model), Zorro III EHCI/PIO driver active','Live driver/tasks; supplied-driver AutoConfig matching','Underlying EHCI silicon and FPGA revision not identified'],
 ['USB root hub descriptor','Philips ISP1520, VID 0471, PID 3526; 3 ports','Live Poseidon descriptors and startup log','Root-hub identity may be supplied by the driver; not proof of the host-controller chip marking'],
 ['Native floppy','DF0: trackdisk.device unit 0, no disk','Live mounted device and Info','Manufacturer/model and DD/HD mechanism not identified'],
 ['External MIDI','Roland MT-32 intended via native serial MIDI adapter','Owner information; CAMD configuration previously verified','MT-32 disconnected; no end-to-end physical test'],
 ['ZZ9000AX audio add-on','Driver and audio modes installed; Music Unit preference selects it','Live files and saved preferences','Physical daughterboard presence and playback remain unconfirmed']]
savecsv('hardware-inventory.csv',['Item','Description','Evidence','Unverified details'],hardware)
mem=[['Accelerator-range Fast RAM','$08000000–$17FFFFFF','256 MiB',40,'$0505','TF4060 attribution consistent with owner hardware and address map'],['Motherboard-range Fast RAM','$01000000–$07FFFFFF','112 MiB',30,'$0505','Motherboard attribution inferred from A4000 address range'],['ZZ9000 Fast RAM','$50000000–$5FFFFFFF','256 MiB',20,'$0405','Directly matched to AutoConfig 28014/5'],['Chip RAM','$00001000–$001FFFFF','2 MiB physical; 2,093,056 bytes reported',-10,'$0703','First 4 KiB excluded from OS-reported total']]
savecsv('memory-map.csv',['Region','Range inclusive','Capacity','Priority','Attributes','Attribution'],mem)
volumes=[['System:','BDH0:','buddha.device / 0','PFS3 / $50465303','19.2',3930841,31353,3899488,'validated; 0 errors'],['HDD50Gig:','BDH1:','buddha.device / 0','PFS3 / $50465303','19.2',54676162,10071862,44604300,'validated; 0 errors'],['SD032G:','SDH0:','2nd.buddha.device / 0','International FFS / DOS\\3 / $444F5303','47.4',30509566,2098258,28411308,'validated; 0 errors']]
savecsv('volumes.csv',['Volume','DOS device','Driver / unit','Filesystem','Registered filesystem version','Usable KiB','Used KiB','Free KiB','State'],volumes)
usbclasses=[[r[1],r[2],r[8]] for r in libs if r[1].endswith('.class')]
source_urls={
 'zz':'https://mnt.computer/media/ZZ9000_info_md/2019-08-09-ZZ9000-resources.html',
 'xacp':'https://github.com/Xanxi-Amiga/XACP-ZZ9000',
 'cf':'https://www.sandisk.com/en-sg/products/memory-cards/cfast-cfexpress-compactflash/sandisk-extreme-compactflash?sku=SDCFXS-064G-X46',
 'freeway':'https://www.amibay.com/threads/used-freeway-usb-cards-official-thread.2437709/',
 'ahi':'https://github.com/aros-development-team/AROS/blob/master/workbench/devs/AHI/Include/C/devices/ahi.h',
 'tf':'https://www.exxosforum.co.uk/forum/viewtopic.php?t=5188',
 'bridge':'https://github.com/geekychris/amiga_mcp'}
section('scope','Scope and evidence',p('Inventory of the real A4000TX at <strong>10.0.0.40</strong>, collected over its AmigaBridge connection on <strong>7 October 2026</strong> (Mac clock). This is a live hardware/OS inventory, supported by prior installation records and clearly identified manufacturer specifications.')+p('<strong>No persistent Amiga configuration, firmware or installed application was changed.</strong> Read-only queries and two small native inventory programs were staged in RAM:; their outputs were copied to this Mac. The disk inquiries were limited to mounted devices and used INQUIRY and READ CAPACITY. No media scan, format, repair, benchmark, reboot or audio playback was performed.')+p('“Live” means reported by this running machine. “Owner” means supplied in the conversation. “Specification” describes a product family, not a physical inspection. “Prior verification” records earlier tests, not a new test today. Unidentified revisions, serials and chip markings remain unknown. This report is an inventory, not a full disk backup.')+p('Collected: <code>'+H(now)+'</code>. Free-memory, task, socket and disk-usage figures are snapshots taken at different points during collection, while ScummVM was running. 1 MiB = 1,048,576 bytes; 1 GiB = 1,073,741,824 bytes; decimal GB = 1,000,000,000 bytes.'))
section('overview','System at a glance',tab(['Area','Verified result'],[
 ['Host','A4000TX (owner identification); active 68060 revision 5; AGA PAL 50 Hz'],
 ['Memory','2 MiB Chip + 624 MiB Fast mapped (256 + 112 + 256 MiB)'],
 ['Graphics / ARM','ZZ9000; Workbench 1920 × 800 at 8 bits/pixel; firmware register $0113; prior XX19c/XACP activation and ARM execution'],
 ['Storage','64.030 GB CF device with System: and HDD50Gig:; 31.243 GB SD-to-CF device with SD032G:; DF0: empty'],
 ['USB','Freeway Triton Z3 driver 1.01; Poseidon 4.5; three-port high-speed root hub; no external USB device enumerated'],
 ['Network','X-Surf 100, Roadshow 1.15; 10.0.0.40/24; bridge TCP 2345 connected'],
 ['OS','Kickstart 47.115 / Exec 47.13; disk version 47.2; workbench.library 47.33 (2021)'],
 ['Inventory coverage',f'{len(libs)} loaded library/class/audio entries; {len(devs)} loaded devices; {len(versions)} installed-component version queries; {len(files):,} SYS: file records']]))
section('hardware','Hardware, processors and chips',tab(['Item','Identification','Evidence','Limits'],hardware)+p('ZZ9000 processor and DDR3 specifications: '+link(source_urls['zz'],'MNT Research product documentation')+'. Accelerator-family context: '+link(source_urls['tf'],'Terrible Fire’s TF4060 design announcement')+'. The accelerator’s advertised maximum clock is not treated as this machine’s measured CPU clock.')+p('<strong>Physical inspection still needed:</strong> motherboard/accelerator/card PCB revisions, CPU mask and date codes, RAM chip brands and populated module sizes, Buster/Ramsey/Gary/Paula/CIA revisions, PSU model/ratings, battery condition, fan models, cabling, monitor make/model and unexposed peripheral serials. No reliable remote temperature, voltage, fan-speed or SMART data was obtained.'))
section('memory','Memory and address map',tab(['Region','Inclusive range','Capacity','Priority','Attributes','Evidence'],mem)+p('Fast RAM total: <strong>654,311,424 bytes = 624 MiB</strong>. Chip RAM reported total: <strong>2,093,056 bytes</strong>. At the initial snapshot, Fast RAM free was 596,232,368 bytes (568.61 MiB) and Chip RAM free was 1,889,728 bytes (1.80 MiB). These live totals supersede the earlier owner estimate of 284 MB Fast RAM.')+p('Exec memory headers begin 32 bytes into each listed region. The address ranges above describe the map; allocation metadata accounts for the small difference in usable memory. Priority 40/30/20/−10 establishes the OS allocation preference, not measured memory speed.')+p('The ZZ9000’s 128 MiB graphics/register aperture is an address window, not another 128 MiB to add to system RAM. Its onboard DDR3, ARM workspace, graphics buffers and exposed 256 MiB Amiga Fast RAM are overlapping uses of the same card memory. Do not add the full card DDR3 specification to the 624 MiB OS total.')+details('Raw ShowConfig and available-memory evidence',pre('showconfig.txt')+pre('avail.txt')))
section('expansion','Expansion boards and identifiers',tab(['Identification','Decimal IDs','Hex IDs','Base','ConfigDev bytes','ROM type','Flags','Serial field'],boards)+p('The X-Surf entry has a 64 KiB ConfigDev subsize, while ShowConfig describes a 64 MiB Zorro III aperture. These are different size fields, not contradictory RAM totals. AutoConfig serial fields can contain model/build constants; “4060”, “6”, “12” and “20230604” are preserved verbatim and are not asserted to be unique manufacturing serial numbers or dates.')+p('Freeway identification was strengthened by inspecting the supplied driver: at file offset $0928 it loads manufacturer $1447 (5191) and product $1E (30), then calls expansion.library FindConfigDev. ShowConfig’s older boards database cannot name that entry. The $13D8/$94 entry is retained as a probable TF4060 function rather than a fully resolved database match.'))
phys=[['buddha.device / 0','SDCFXS-064G (INQUIRY fields “SDCFXS-0” + “64G”)','HDX1','125,059,072 × 512','64,030,244,864 bytes / 59.6328 GiB','System: and HDD50Gig:','CompactFlash; model matches SanDisk Extreme family'],['2nd.buddha.device / 0','FC-1307 / SD to CF Adapter','“Rev ” (literal truncated field)','61,022,208 × 512','31,243,370,496 bytes / 29.0977 GiB','SD032G:','SD card behind adapter; underlying SD maker/model/serial not exposed']]
section('storage','Physical drives, partitions and filesystems',tab(['Driver / unit','Reported identity','Revision','Capacity geometry','Raw capacity','Mounted volumes','Type'],phys)+p('The CF identification is based on the live drive model and '+link(source_urls['cf'],'SanDisk’s SDCFXS product specification')+'. Inquiry data is translated through the Buddha IDE driver. No drive serial was returned by the optional VPD query; firmware strings may be truncated. The SD adapter identifies itself rather than the card behind it. Both devices are solid-state media; the label “HDD50Gig” does not identify a rotating hard drive.')+tab(['Volume','DOS device','Driver','Filesystem','Registered version','Usable GiB','Used GiB','Free GiB','State'],[[*v[:5],f'{v[5]/1048576:.3f}',f'{v[6]/1048576:.3f}',f'{v[7]/1048576:.3f}',v[8]] for v in volumes])+p('Mounted-volume figures are filesystem-reported usable space. Raw device capacity and cylinder extents include space the filesystem does not report as usable; these figures should not be substituted for one another. FileSystem.resource reports PFS3 19.2 and FFS 47.4; this identifies registered handlers, not a byte-for-byte verification of each disk’s RDB handler image.')+tab(['Partition','Cylinders','Heads × sectors/track','Extent GiB','Sectors/block','Buffers','MaxTransfer','Mask'],[
 ['BDH0','2–7742','16 × 68','4.0160','1 (default)','150','$00FFFFFF','$7FFFFFFE'],['BDH1','7743–114942','16 × 68','55.6152','8','150','$00FFFFFF','$7FFFFFFE'],['SDH0','2–39727','6 × 256','29.0962','2','80','$0001FE00','$7FFFFFFE']])+p('DF0: is mounted through trackdisk.device unit 0 with a 2-head, 80-cylinder, 11-sector default geometry (880 KiB DD layout); no disk was present. This does not establish the drive’s manufacturer or whether the mechanism supports HD media. RAM: is a dynamic memory filesystem, not a separate physical drive. No optical drive, SFS volume or USB mass-storage volume was mounted at this snapshot.')+details('MountInfo, Info and registered filesystem evidence',pre('info.txt')+''.join(pre('mount-'+n+'.txt') for n in ['BDH0','BDH1','SDH0','DF0'])+pre('filesystems.tsv')))
section('usb','USB ports and attached devices',p('The <strong>Freeway Triton Zorro III controller is active</strong>. The live startup log reports a root hub with <strong>three ports</strong>, successfully configured, with QuickIO enabled. The driver is <code>freewaytritonz3usb.device 1.01 (2022.05.16)</code>; Poseidon is <code>4.5 (14.10.2014)</code>. The host task and PIO transfer task are present.')+tab(['Property','Observed value'],[['Hub descriptor','Philips Semiconductors ISP1520'],['Vendor / product','0471 / 3526'],['USB version / reported speed','USB 2.00 / high-speed'],['Device address / class','Address 1; class 9, subclass 0, protocol 1 (single-TT hub)'],['Serial / device revision','n/a / 0000'],['External devices now','None enumerated'],['Driver mode','Zorro III EHCI / PIO'],['Stack persistence','S:User-Startup runs ENVARC:PsdStackloader'],['FAT media support','L:fat95 3.18, dated 1 March 2013; loaded when needed']])+p('The descriptor’s self-powered/0 mA fields do not measure available port current. The reported three ports do not identify which case connector corresponds to each port, nor prove every physical socket under load. '+link(source_urls['freeway'],'The supplier’s Freeway specification')+' describes three USB connectors and USB 2.0 support; USB signalling speed is not actual Amiga file-transfer throughput.')+p('The available Poseidon log contains severity-0 startup messages and no higher-severity errors. Its informal “blame” and “laugh” messages are normal class-loading text. USB storage was successfully used earlier according to the owner, but no storage stick is attached now. The earlier DrawBridge/USB floppy is historical and is not a mounted native floppy or USB mass-storage device in this snapshot.')+details('Loaded USB classes and versions',tab(['Class','Header version','Embedded ID/date'],usbclasses))+details('USB descriptor and event-log evidence',pre('usb-root.txt')+pre('usb-errors.txt')))
section('ports','Ports and I/O coverage',tab(['Interface','Identification / present evidence','Current use / verification limit'],[
 ['Freeway USB','Three root-hub ports; owner identifies Triton Lite','Controller enumerated; no external device attached; individual socket wiring not inspected'],
 ['X-Surf Ethernet','Active x-surf-100.device / unit 0','Live Ethernet link carrying the bridge connection'],
 ['ZZ9000 Ethernet','Connector is part of the manufacturer specification','Not the active Roadshow interface; no live ZZ9000 network driver observed'],
 ['ZZ9000 USB','Separate USB storage connector in the manufacturer specification','Not covered by Freeway/Poseidon enumeration; no mounted volume from it'],
 ['ZZ9000 firmware microSD','BOOT.bin storage recorded in the previous firmware update','Separate from SD032G:; zzsd.device 43.20 is resident with open count 0; no mounted DOS volume'],
 ['ZZ9000 digital video / native video capture','RTG Workbench and native ScummVM screens exist','Physical connector/cable, capture-board revision and monitor EDID not read'],
 ['Buddha IDE','buddha.device / 0 and 2nd.buddha.device / 0','Two physical storage devices currently mounted'],
 ['TF4060 IDE','ehide.device 1.2 (21 April 2024) resident','Open count 0; no mounted DOS volume through this driver'],
 ['Native serial / MIDI','Configured CAMD internal serial port','Intended MT-32 path; instrument disconnected and physical transfer untested'],
 ['Native floppy','DF0: via trackdisk.device / 0','No disk; drive mechanism and connector cabling unverified'],
 ['Keyboard, mouse, joystick and parallel','OS keyboard/input/gameport interfaces present','Physical device models, chosen connector types, port occupancy and parallel hardware not inventoried']])+p('ZZ9000 auxiliary-port capabilities are from '+link(source_urls['zz'],'MNT documentation')+'. Its firmware microSD is distinct from the Buddha-connected SD card. No unsupported inference is made from installed drivers to attached peripherals.'))
section('network','Networking and remote access',tab(['Property','Live result'],[['Interface','x-surf-100; device x-surf-100.device unit 0'],['Driver','1.16 (3 September 2018)'],['MAC address','28:CD:4C:FF:F2:B2'],['IPv4 / mask','10.0.0.40 / 255.255.255.0'],['Binding','Dynamic (DHCP), according to Roadshow'],['Gateway','10.0.0.1'],['DNS','10.0.0.1 listed twice: dynamic and static'],['MTU / reported link speed','1500 bytes / 100,000,000 bits/s'],['TCP/IP stack','Roadshow 1.15; bsdsocket.library 4.364 (1 September 2023), 68020+ build'],['Roadie','1.3.9 (20 December 2021)'],['Listening TCP socket','0.0.0.0:2345'],['Connected bridge client','10.0.0.21:63432 → 10.0.0.40:2345'],['UDP sockets','None shown at snapshot'],['SFTP/FTP server','No separate listening SFTP/FTP socket shown; earlier file-transfer setup is not evidence of a running server now']])+p('The detailed snapshot reports <strong>886 buffer overruns</strong>, 1 dropped packet in its aggregate field, and separate in/out drop counters of 0/2. These counters have different meanings and are preserved verbatim. Connectivity is working; one cumulative snapshot cannot establish when the overruns occurred or whether they are increasing. A later comparison under a controlled transfer would clarify whether tuning is useful. No counters were reset.')+p('The DHCP lease date displayed as 10/10/2033 is not a reliable wall-clock reference because the Amiga clock differs from the Mac. The duplicate DNS address is a configuration redundancy, not proof of a service failure.')+details('Detailed interface and socket evidence',pre('interface.txt')+pre('sockets.txt')))
audioprefs=json.loads((R/'audio-preferences.json').read_text())
section('audio','Audio and MIDI configuration',tab(['Component','Installed / loaded version'],[['ahi.device',ver('SYS:Devs/ahi.device')],['AHI preferences',ver('SYS:Prefs/AHI')],['Paula output',ver('SYS:Devs/AHI/paula.audio')],['ZZ9000AX output',ver('SYS:Devs/AHI/ZZ9000AX.audio')],['File output',ver('SYS:Devs/AHI/filesave.audio')],['MHI ZZ9000',ver('SYS:Libs/MHI/mhizz9000.library')],['CAMD',ver('SYS:Libs/camd.library')],['MidiPorts preferences',ver('SYS:Prefs/MidiPorts')]])+p('Saved <code>ENVARC:Sys/ahi.prefs</code> settings, decoded using the '+link(source_urls['ahi'],'AHI preference structure')+' and the installed AudioModes definitions:')+tab(['Unit','Mode ID','Saved output mode','Frequency Hz','Channel field'],[['Music Unit (255)' if a['unit']==255 else str(a['unit']),a['mode'],a['mode_name'],a['frequency_hz'],a['channels']] for a in audioprefs])+p('These are <strong>saved preferences</strong>, not a claim about every application’s active mixer format. ScummVM’s AHI mixer task, ahi.device and paula.audio were loaded during the audit. The Music Unit selects ZZ9000AX, but software installation and a preference selection do not establish that the AX daughterboard is physically fitted or audible.')+p('The prior ScummVM setup enabled CAMD’s internal serial port and verified the in.0/out.0 clusters. ScummVM is configured for CAMD/native MT-32. The owner said the Roland is not connected; no MIDI notes were sent during this audit and no physical MT-32 response is claimed.'))
section('os','Operating system, libraries and dates',tab(['Layer','Reported version / date','Interpretation'],[['Kickstart','47.115','Live ROM/system version; owner identifies OS release as 3.2.3'],['Exec','47.13 (1 January 2025)','Loaded system kernel'],['Intuition','47.53 (27 November 2024)','Loaded ROM/system component'],['DOS','47.30','Loaded header; no ID date exposed'],['Disk version','47.2 (10 April 2021)','version.library on disk and in memory'],['Workbench library','47.33 (31 March 2021)','Loaded and installed older disk component'],['SetPatch','47.4 (4 August 2020)','Installed executable'],['68060.library','47.2 (6 July 2022)','Loaded CPU support'],['mmu.library','47.10 (26 August 2025)','Loaded MMU support'],['MUI','muimaster.library 19.35 (12 February 1997)','Loaded version'],['AmiSSL','amisslmaster 5.23 / amissl_v353 5.23 (17 September 2025)','Installed; not present in initial loaded-library snapshot'],['Icon library','51.4 header; ID 51.4.600 (TC020)','Third-party replacement; header and full build identifier differ']])+p('<strong>OS consistency finding:</strong> this machine combines 2024/2025 ROM components with 2021 Workbench/disk components. The owner’s “OS 3.2.3” label should therefore be recorded alongside the actual versions, rather than used to certify a complete matching disk update. A future comparison against the owner’s registered 3.2.3 installation media can establish which disk files need updating; this audit has not installed or replaced them.')+p('<strong>Clock finding:</strong> the Mac reported 7 October 2026; the Amiga Date command returned <code>Thursday 09-Oct-25 16:20:43</code>. Numerous files also retain 1980 or archive-era timestamps. An embedded $VER date describes a component build/release; a filesystem timestamp describes stored metadata. Neither establishes installation date, hardware manufacture date or the age of this particular machine. Dates are preserved in their original formats in the CSVs.')+p('The tables distinguish loaded header versions, embedded ID strings and <code>Version FILE FULL</code> results. For example, ZZ9000.card’s loaded header says 1.0 while its embedded/file version says 1.13. That does not mean the wrong card firmware is running.'))
section('graphics','Graphics, ARM firmware and previous tests',tab(['Item','Result / status'],[['Native display','AGA PAL; 50 Hz VBlank; E-clock 709,379 Hz (not CPU clock)'],['Workbench screen','1920 × 800 × 8 bits/pixel'],['ScummVM screen','320 × 200 × 8 bits/pixel; active during audit'],['RTG core','rtg.library 43.538; Picasso96API.library 2.455; emulation.library 41.525 (29 July 2023)'],['Monitor driver',ver('SYS:Devs/Monitors/ZZ9000')],['ZZ9000 card driver',ver('SYS:Libs/Picasso96/ZZ9000.card')],['Current firmware register','$0113 at ZZ9000 base $40000000'],['Installed firmware record','BOOT_XX19c.bin, XACP 1.7; previous update and reboot/handshake verified'],['Firmware SHA-256','2b6a4224d4645694ef4d186baae14a86c100f4ce9e15033262a814cc239e7305'],['Patch suffix caveat','Register $0113 identifies the 1.19 family; XX19c suffix comes from the recorded installed artifact, not fresh full-flash readback']])+p('Prior hardware tests recorded ZZBenchGUI 1.3 ARM Core1 execution and XACP dispatch, followed by owner-confirmed ZZQuake display. The protocol and firmware project is '+link(source_urls['xacp'],'XACP-ZZ9000')+'. These tests establish usable ARM execution through XACP; they do not establish source-level ARM debugging support.')+tab(['Prior ZZBench metric','68060','ARM Core1'],[['Integer MIPS','53.36','1061.77'],['Floating-point MWIPS','42.77','917.31']])+p('The earlier benchmark displayed ARM DDR read/write/copy as 0.0 MB/s; that subtest remains unresolved and is not presented as a valid memory-health or bandwidth result. No benchmark was rerun for this inventory.'))
apps=[['AmigaBridge','SD032G:amiga-bridge/amiga-bridge','150,204 bytes; build/version from prior records: 1.20','Live AMIGABRIDGE port and TCP connection; Version FILE found no standard tag'],['Bridge network watcher','C:bridge-netwatch; S:Start-Amiga-Bridge-Auto','Custom native helper; no standard version tag','Live SIXIES.BRIDGE.NETWATCH port/task; starts bridge when interface has an IP'],['Roadie','HDD50Gig:Roadie','1.3.9 (2021-12-20)','Live ROADIE port/task'],['ScummVM','HDD50Gig:Games/ScummVM','AGA 68060 package 2.5.1.40; executable identifies 2.5.1, built 4 September 2026','Running; CAMD/MT-32 configured; no games added by our installation'],['ZZQuake','HDD50Gig:Games/ZZQuake','1.0; shareware Quake data','Prior installed/owner-confirmed display; not running at snapshot'],['ZZBenchGUI','SD032G:Drivers/XACP/ZZBench/ZZBenchGUI_v1.3','1.3','Prior native 68k/ARM test results retained'],['ZZ9000 firmware payload','SD032G:Drivers/XACP/BOOT_XX19c.bin','XX19c / XACP 1.7','Staged artifact and previous installation record'],['ARexx','SYS:System/RexxMast; rexxsyslib.library','47.2 library (19 August 2019)','RexxMaster task and REXX/AREXX public ports present']]
section('services','Applications, startup and running services',tab(['Application/service','Location','Version','Evidence'],apps)+p('AmigaBridge originates from '+link(source_urls['bridge'],'geekychris/amiga_mcp')+' with workspace adaptations; the separate bridge-netwatch helper was built for this installation. The bridge’s uptime tool reported 18 minutes 33 seconds at the initial snapshot; source inspection shows this counts from bridge initialization, not system boot. The Mac-side dashboard is at localhost:55010 and the real Amiga listens on TCP 2345. Simulator/emulator results are not used as hardware evidence.')+p('Startup currently invokes Roadshow networking, Poseidon’s saved stack loader, RexxMast and the bridge network watcher. The watcher checks for an active interface/address and avoids duplicate bridge processes. Its previous controlled restart tests passed; a cold-boot or Roadie disconnect/reconnect test is not newly certified by this report.')+p('<strong>Confirmed stale startup entries:</strong> <code>S:User-Startup</code> runs <code>SYS:C/StikyRMB</code>, which is absent; <code>S:Startup-Sequence</code> runs <code>HDD50Gig:VisualPrefs</code>, which is absent. These lines may produce launch errors. Their intended replacements/paths should be checked before any edit.')+details('Public ports, tasks, assigns and WBStartup inventory',''.join('<pre>'+H(o['text'])+'</pre>' for o in json.loads((R/'live-overview.json').read_text()) if o['tool'] in ['amiga_list_tasks','amiga_list_ports','amiga_list_assigns'])+pre('wbstartup.txt')))
section('recommendations','Findings and recommendations',tab(['Priority','Finding','Recommended follow-up'],[['Review','Clock differs by almost a year','Set the correct date/time and check RTC persistence when convenient; confirm the Mac date too before changing either clock.'],['Review','Mixed ROM and Workbench/disk component generations','Compare installed disk files with the owner’s 3.2.3 update manifest before doing a coordinated update.'],['Review','Missing StikyRMB and VisualPrefs startup targets','Locate the intended programs and correct or remove stale startup entries after checking their purpose.'],['Observe','X-Surf cumulative overruns','Compare counters before/after a controlled transfer; investigate only if overruns continue to grow or performance suffers.'],['Confirm','AHI Music Unit selects ZZ9000AX','Confirm AX hardware/output exists before relying on that preference; current ScummVM path uses loaded Paula audio.'],['Document','CPU clock, board revisions and physical chip markings unknown','Record component labels/photos during a future powered-off inspection; no need to infer them from benchmark speed.'],['Reconcile','Earlier Fast RAM estimate was 284 MB','Use the live 624 MiB map for the system record, retaining attribution caveats for the two non-ZZ banks.'],['Retest later','ZZBench ARM DDR subtest showed zero','Treat its memory-bandwidth result as unvalidated; CPU/XACP execution was verified separately.']])+p('Positive observations: bridge connected, network interface up, ARexx running, AHI/Paula loaded, Freeway controller/root hub configured, and mounted persistent filesystems validated with zero reported errors. These are operational snapshots, not exhaustive hardware stress tests.'))
section('libraries','Complete loaded libraries, classes and devices',p(f'{len(libs)} library-list entries and {len(devs)} device-list entries captured directly from Exec. Open count 0 means the object is resident but currently unused; it is not an error. USB class-provided device entries can exist without attached hardware. The bridge overview initially saw 76 libraries; ShowConfig subsequently loaded boards.library, giving {len(libs)} in the native snapshot.')+'<label class="filter">Filter loaded entries <input type="search" data-filter="loaded-table" placeholder="e.g. 68060, USB, 2025"></label>'+tab(['Kind','Name','Header version','Opens','Base','Embedded ID / date'],[[*r[:5],r[8]] for r in loaded],'loaded-table')+p('CSV: '+link('loaded-libraries-and-devices.csv','Loaded libraries and devices')+'.')+details('Registered Exec resource names',tab(['Resource','Address'],resources)))
section('installed','Installed component versions and file dates',p('These 494 queries cover selected components in C:, L:, Libs, Classes, Devs, Prefs, System, Tools, Utilities, MUI and AmiSSL. Some data files have no version tag; this is recorded rather than treated as failure. This is not a complete executable/version scan of the games and application data volumes.')+'<label class="filter">Filter installed components <input type="search" data-filter="installed-table" placeholder="e.g. AmiSSL, 68060, fat95"></label>'+tab(['Path','Version FILE FULL / embedded date','Bytes','Filesystem date','Time','Protection'],versions,'installed-table')+p('CSV: '+link('installed-component-versions.csv','Installed component versions')+'. Full SYS: metadata listing: '+link('system-files.csv','2,763 system file records')+'. File timestamps are not trusted installation dates.'))
section('evidence','Evidence files and reproducibility',p('The companion ZIP includes this HTML report, CSV/JSON inventories, raw read-only query output and the native probe sources. It excludes Amiga OS binaries, game assets and third-party driver binaries. The report opens locally without network dependencies and includes filters for the large tables. Browser Print / Save as PDF can print the narrative and loaded-library inventory; the 494-row installed table is intentionally omitted from print and remains in HTML/CSV.')+tab(['Artifact','Purpose'],[['hardware-inventory.csv','Hardware identification with evidence and unknowns'],['expansion-boards.csv','Six AutoConfig entries and raw IDs'],['memory-map.csv','RAM ranges and allocation priorities'],['volumes.csv','Persistent volume capacity/usage and filesystems'],['loaded-libraries-and-devices.csv','Native Exec inventory and embedded ID strings'],['installed-component-versions.csv','494 Version FILE FULL results with file metadata'],['system-files.csv','2,763 files under SYS: with sizes/dates/protection'],['audio-preferences.json','Saved AHI unit settings'],['native.tsv / filesystems.tsv','Raw native probe results'],['live-overview.json','Timestamped bridge overview'],['inventory.c / filesystems.c','Read-only native probe source'],['report-data.json','Machine-readable summary'],['SHA256SUMS.txt','Checksums for bundled evidence']])+p('Collection limits: no full disk image or sector scan; no per-chip physical inspection; no raw flash/RDB checksum audit; no new ARexx execution/source-debugging test; no exhaustive executable inventory of HDD50Gig: or SD032G:. The inventory does not prove that every installed library is ABI-compatible or every hardware port works under load.'))
css='''
:root{color-scheme:light;--ink:#162330;--muted:#526779;--accent:#007d8a;--line:#d7e2e8;--bg:#f3f6f8}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}header{background:#122d3b;color:white;padding:48px max(5vw,24px) 36px}header .eyebrow{letter-spacing:.14em;text-transform:uppercase;color:#89dce1;font-size:12px}h1{font-size:44px;line-height:1.1;margin:12px 0}header p{max-width:900px;color:#d3e5ee}.chips{display:flex;flex-wrap:wrap;gap:10px}.chips span{border:1px solid #48636f;border-radius:20px;padding:5px 14px;font-size:13px}main{max-width:1500px;margin:auto;padding:26px}nav{display:flex;flex-wrap:wrap;gap:8px 18px;padding:20px 0 28px}nav a{text-decoration:none;font-size:13px}a{color:#006b78}section{background:white;border:1px solid var(--line);border-radius:10px;padding:26px;margin:0 0 24px;scroll-margin-top:20px}h2{font-size:24px;margin:0 0 18px}p{max-width:1120px;margin:14px 0}table{width:100%;border-collapse:collapse;font-size:13px;line-height:1.45}th{text-align:left;background:#eaf1f5;color:#284753;font-weight:650}td,th{padding:10px 12px;border-bottom:1px solid var(--line);vertical-align:top;overflow-wrap:anywhere}tr:nth-child(even){background:#f9fbfc}.table-wrap{overflow:auto;margin:18px 0}td:first-child{font-weight:550}.loaded-table td:nth-child(2),.loaded-table td:nth-child(5){white-space:nowrap}pre{font:12px/1.5 ui-monospace,Menlo,monospace;white-space:pre-wrap;overflow-wrap:anywhere;background:#f2f6f8;border:1px solid var(--line);padding:16px;border-radius:6px}code{font-size:13px;background:#edf3f5;padding:2px 4px}details{margin:16px 0;border-top:1px solid var(--line);padding-top:12px}summary{cursor:pointer;font-weight:600;color:#24616b}.filter{display:flex;align-items:center;gap:14px;font-size:13px;font-weight:600}input{padding:10px 14px;border:1px solid #afc5ce;border-radius:6px;width:330px;max-width:100%;font:inherit}footer{padding:20px 0;color:var(--muted);font-size:12px}button{padding:10px 16px;border:1px solid #93c0c8;border-radius:6px;background:#e6f7f7;color:#164752;font:inherit;cursor:pointer}.actions{display:flex;gap:12px;align-items:center;margin-top:22px}.actions a{color:#b8f3f3}.kpi{font-size:18px}
@media(max-width:700px){main{padding:12px}section{padding:16px}h1{font-size:34px}td,th{padding:8px}.filter{display:block}input{display:block;margin-top:8px}}
@media print{body{background:white;font-size:10pt}header{background:white!important;color:#132e3e;padding:0 0 16px;border-bottom:3px solid #007d8a}header p,header .eyebrow{color:#284753}.chips span{border-color:#cad9df}.actions,nav,.filter,#installed,.no-print{display:none!important}main{max-width:none;padding:0}section{border:0;border-radius:0;padding:14px 0;margin:0}h2{font-size:17pt;break-after:avoid}table{font-size:8pt}thead{display:table-header-group}tr{break-inside:avoid}td,th{padding:5px 6px}.table-wrap{overflow:visible}details{display:none}a{color:inherit;text-decoration:none}h1{font-size:30pt}@page{size:A4 landscape;margin:14mm}}
'''
nav='<nav aria-label="Report sections">'+''.join('<a href="#'+i+'">'+H(t)+'</a>' for i,t,b in sections)+'</nav>'
script='''document.querySelectorAll('[data-filter]').forEach(input=>input.addEventListener('input',()=>{const q=input.value.toLowerCase();document.querySelectorAll('.'+input.dataset.filter+' tbody tr').forEach(tr=>tr.hidden=!tr.textContent.toLowerCase().includes(q));}));window.addEventListener('beforeprint',()=>document.querySelectorAll('tr[hidden]').forEach(tr=>{tr.hidden=false;}));'''
report='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>A4000TX — System Inventory — 7 October 2026</title><style>'+css+'</style></head><body><header><div class="eyebrow">Real hardware · Read-only inventory · 7 October 2026</div><h1>Amiga A4000TX</h1><p class="kpi">Hardware, processors, memory, storage, USB, operating system and component versions.</p><div class="chips"><span>68060 rev 5</span><span>2 MiB Chip + 624 MiB Fast</span><span>AGA + ZZ9000</span><span>XACP / ARM Core1</span><span>10.0.0.40</span></div><div class="actions"><button onclick="window.print()">Print / Save as PDF</button><a href="A4000TX-System-Report.pdf">PDF report</a><a href="installed-component-versions.csv">Component inventory CSV</a></div></header><main>'+nav+''.join(b for i,t,b in sections)+'<footer>Generated '+H(now)+' · Live evidence, owner information and prior test records are distinguished throughout.</footer></main><script>'+script+'</script></body></html>'
(R/'A4000TX-System-Report.html').write_text(report,encoding='utf-8')
data={'generated_utc':now,'target':'10.0.0.40','amiga_clock':read('date.txt'),'hardware':hardware,'memory':mem,'boards':boards,'physical_drives':phys,'volumes':volumes,'loaded_entries':loaded,'installed_versions':versions,'system_files_count':len(files),'sources':source_urls,'audio_preferences':audioprefs,'persistent_amiga_changes':False,'probe_staging':'RAM:'}
(R/'report-data.json').write_text(json.dumps(data,indent=2,ensure_ascii=False),encoding='utf-8')
print('Report',len(report),'bytes;',len(libs),'libraries;',len(devs),'devices;',len(versions),'version records;',len(files),'system files')
